import { CategoryInfo, Place } from './types';

export const EVENT_DETAILS = {
  title: 'V ENCONTRO SAÚDE NAS FRONTEIRAS',
  subTitle: 'BRASIL - PARAGUAI',
  dateLabel: '18 e 19 DE AGOSTO DE 2026',
  schedule: [
    { day: '18/08 (Terça-feira)', hours: '15h às 21h', label: 'Credenciamento e Sessão de Abertura' },
    { day: '19/08 (Quarta-feira)', hours: '08h às 17h', label: 'Painéis Técnicos e Encerramento' },
  ],
  venue: {
    name: 'GRAND PARK HOTEL',
    address: 'Av. Afonso Pena, 5282 - Chácara Cachoeira, Campo Grande - MS, 79040-010',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Grand+Park+Hotel+Av+Afonso+Pena+5282+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Grand%20Park%20Hotel%20Campo%20Grande',
    phone: '(67) 3044-4444',
    siteUrl: 'http://www.grandparkhotel.com.br',
    instagramUrl: 'https://www.instagram.com/grandparkhotelcg',
  },
  organizers: [
    { acronym: 'SVS', name: 'Superintendência de Vigilância em Saúde' },
    { acronym: 'SES', name: 'Secretaria de Estado de Saúde' },
    { acronym: 'MS', name: 'Governo do Estado de Mato Grosso do Sul' },
  ],
};

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'hoteis',
    code: '01',
    title: 'Hotéis e Hospedagens',
    subtitle: 'Local oficial do evento e opções de hospedagem próximas',
    iconName: 'Hotel',
    accentBorder: 'border-[#0F2C59]',
    accentText: 'text-[#0F2C59]',
    accentBg: 'bg-blue-50',
    badgeColor: 'bg-[#0F2C59] text-white',
  },
  {
    id: 'gastronomia',
    code: '02',
    title: 'Restaurantes e Gastronomia',
    subtitle: 'Churrascarias tradicionais, culinária regional, petiscos e hambúrgueres',
    iconName: 'Utensils',
    accentBorder: 'border-[#DA291C]',
    accentText: 'text-[#DA291C]',
    accentBg: 'bg-red-50',
    badgeColor: 'bg-[#DA291C] text-white',
  },
  {
    id: 'compras',
    code: '03',
    title: 'Compras e Entretenimento',
    subtitle: 'Shopping centers, hipermercados e arenas culturais',
    iconName: 'ShoppingBag',
    accentBorder: 'border-[#00874E]',
    accentText: 'text-[#00874E]',
    accentBg: 'bg-emerald-50',
    badgeColor: 'bg-[#00874E] text-white',
  },
  {
    id: 'parques',
    code: '04',
    title: 'Parques, Bioparque e Órgãos',
    subtitle: 'Bioparque Pantanal, áreas verdes emblemáticas e instituições públicas',
    iconName: 'Trees',
    accentBorder: 'border-[#009E52]',
    accentText: 'text-[#009E52]',
    accentBg: 'bg-teal-50',
    badgeColor: 'bg-[#009E52] text-white',
  },
];

export const PLACES: Place[] = [
  // ==================== 01. HOTÉIS E HOSPEDAGENS ====================
  {
    id: 'grand-park-hotel',
    name: 'Grand Park Hotel',
    category: 'hoteis',
    isVenue: true,
    description: 'Local Oficial do V Encontro Saúde nas Fronteiras. Hotel executivo completo com centro de convenções, piscina, restaurante e acesso privilegiado na principal avenida da cidade.',
    siteUrl: 'http://www.grandparkhotel.com.br',
    siteLabel: 'grandparkhotel.com.br',
    instagramUrl: 'https://www.instagram.com/grandparkhotelcg',
    instagramHandle: '@grandparkhotelcg',
    highlightTag: 'LOCAL OFICIAL DO EVENTO',
    addressInfo: 'Av. Afonso Pena, 5282 - Chácara Cachoeira, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Grand+Park+Hotel+Av+Afonso+Pena+5282+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Grand%20Park%20Hotel%20Campo%20Grande',
    features: ['Sede do Evento', 'Wi-Fi de Alta Velocidade', 'Restaurante & Café', 'Estacionamento Próprio'],
  },
  {
    id: 'manhattan-flat',
    name: 'Manhattan Flat',
    category: 'hoteis',
    description: 'Flat executivo com unidades completas para hospedagem com autonomia, próximo ao Shopping Campo Grande e ao Grand Park Hotel.',
    siteUrl: null,
    siteLabel: 'Disponível em plataformas de reserva (Booking, Airbnb)',
    instagramUrl: 'https://www.instagram.com/manhattanflat',
    instagramHandle: '@manhattanflat',
    highlightTag: 'Flat Executivo',
    addressInfo: 'R. Roberto Spengler, 243 - Chácara Cachoeira, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Manhattan+Flat+Roberto+Spengler+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Manhattan%20Flat%20Campo%20Grande',
    features: ['Cozinha Equipada', 'Recepção 24h', 'A 5 min do evento'],
  },
  {
    id: 'olga-kehdi-residence',
    name: 'Olga Kehdi Residence',
    category: 'hoteis',
    description: 'Residencial com apartamentos mobiliados e serviço de hotelaria, muito bem avaliado em plataformas de turismo.',
    siteUrl: 'https://www.booking.com/hotel/br/olga-kehdi-flats.pt-br.html',
    siteLabel: 'Reserva no Booking.com',
    instagramUrl: 'https://www.instagram.com/olgakehdiresidence',
    instagramHandle: '@olgakehdiresidence',
    highlightTag: 'Flats & Suítes',
    addressInfo: 'R. Raul Pires Barbosa, 1374 - Chácara Cachoeira, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Olga+Kehdi+Residence+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Olga%20Kehdi%20Residence%20Campo%20Grande',
    features: ['Apartamentos Completos', 'Estacionamento Grátis', 'Bairro Nobre e Seguro'],
  },

  // ==================== 02. RESTAURANTES E GASTRONOMIA ====================
  {
    id: 'nativas-grill',
    name: 'Churrascaria Nativas Grill',
    category: 'gastronomia',
    description: 'Referência em rodízio de carnes nobres sul-mato-grossenses, bufê farto de saladas, queijos importados, frutos do mar e culinária japonesa.',
    siteUrl: 'https://churrascariacampogrande.com.br',
    siteLabel: 'churrascariacampogrande.com.br',
    instagramUrl: 'https://www.instagram.com/nativasgrillcampogrande',
    instagramHandle: '@nativasgrillcampogrande',
    highlightTag: 'Rodízio Premium',
    addressInfo: 'Av. Afonso Pena, 5468 - Chácara Cachoeira, Campo Grande - MS (Ao lado do Grand Park)',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Churrascaria+Nativas+Grill+Av+Afonso+Pena+5468+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Churrascaria%20Nativas%20Grill%20Campo%20Grande',
    features: ['Carnes Nobres & Picanha', 'Buffet Completo', 'Ao lado do Hotel do Evento', 'Ambiente Climatizado'],
  },
  {
    id: 'poia-espeto',
    name: 'Poiá Espeto',
    category: 'gastronomia',
    description: 'Tradicional espetaria com cortes generosos grelhados na brasa, acompanhados de mandioca amarela pantaneira derretendo e vinagrete da casa.',
    siteUrl: 'http://poiaespeto.com.br',
    siteLabel: 'poiaespeto.com.br',
    instagramUrl: 'https://www.instagram.com/poiaespetocg',
    instagramHandle: '@poiaespetocg',
    highlightTag: 'Tradição Pantaneira',
    addressInfo: 'R. Antônio Maria Coelho, 3923 - Jardim dos Estados, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Poia+Espeto+Rua+Antonio+Maria+Coelho+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Poia%20Espeto%20Campo%20Grande',
    features: ['Espetos Clássicos', 'Mandioca Pantaneira', 'Cervejas Especiais', 'Espaço Aconchegante'],
  },
  {
    id: 'barzito',
    name: 'BarZito',
    category: 'gastronomia',
    description: 'Bar e gastrobar animado com drinks autorais, porções caprichadas, chopp trincando e ambiente agradável para confraternização pós-evento.',
    siteUrl: 'https://www.barzitocg.com',
    siteLabel: 'barzitocg.com',
    instagramUrl: 'https://www.instagram.com/barzitocg',
    instagramHandle: '@barzitocg',
    highlightTag: 'Bar & Happy Hour',
    addressInfo: 'R. Folclore, 29 - Carandá Bosque, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=BarZito+Rua+Folclore+29+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=BarZito%20Campo%20Grande',
    features: ['Chopp Artesanal', 'Coquetelaria Criativa', 'Petiscos de Boteco', 'Happy Hour'],
  },
  {
    id: 'canto-do-cupim',
    name: 'Canto do Cupim',
    category: 'gastronomia',
    description: 'Especialista no autêntico cupim casqueirado e pratos regionais servidos em porções fartas com farofa e acompanhamentos típicos.',
    siteUrl: 'http://www.cantodocupim.com.br',
    siteLabel: 'cantodocupim.com.br',
    instagramUrl: 'https://www.instagram.com/cantodocupim',
    instagramHandle: '@cantodocupim',
    highlightTag: 'Cupim Casqueirado',
    addressInfo: 'Av. Bom Pastor, 261 - Vilas Boas (Corredor Gastronômico), Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Canto+do+Cupim+Av+Bom+Pastor+261+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Canto%20do%20Cupim%20Campo%20Grande',
    features: ['Cupim Casqueirado', 'Corredor Gastronômico Bom Pastor', 'Almoço & Jantar'],
  },
  {
    id: 'el-parrudo-burger',
    name: 'El Parrudo Burger',
    category: 'gastronomia',
    description: 'Hamburgueria artesanal de alta qualidade, com blends grelhados na brasa/parrilla, queijos fundidos e molhos artesanais exclusivos.',
    siteUrl: 'https://elparrudoburger.com.br',
    siteLabel: 'elparrudoburger.com.br',
    instagramUrl: 'https://www.instagram.com/elparrudoburger',
    instagramHandle: '@elparrudoburger',
    highlightTag: 'Burger na Brasa',
    addressInfo: 'R. Nortelândia, 642 - Santa Fé, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Parrudo+Burger+Rua+Nortelandia+642+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=El%20Parrudo%20Burger%20Campo%20Grande',
    features: ['Blend na Parrilla', 'Batatas Crocantes', 'Pão Artesanal', 'Salão & Delivery'],
  },

  // ==================== 03. COMPRAS E ENTRETENIMENTO ====================
  {
    id: 'shopping-campo-grande',
    name: 'Shopping Campo Grande',
    category: 'compras',
    description: 'Principal e mais tradicional shopping center de Mato Grosso do Sul, com centenas de lojas de marcas nacionais e internacionais, praça de alimentação completa e cinema.',
    siteUrl: 'https://shoppingcampogrande.com.br',
    siteLabel: 'shoppingcampogrande.com.br',
    instagramUrl: 'https://www.instagram.com/shoppingcampogrande',
    instagramHandle: '@shoppingcampogrande',
    highlightTag: 'Centro de Compras & Serviços',
    addressInfo: 'Av. Afonso Pena, 4909 - Santa Fé, Campo Grande - MS (A 3 min do hotel do evento)',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shopping+Campo+Grande+Av+Afonso+Pena+4909+MS',
    wazeUrl: 'https://waze.com/ul?q=Shopping%20Campo%20Grande',
    features: ['Lojas & Grifes', 'Praça de Alimentação', 'Cinemark', 'Bancos & Farmácias'],
  },
  {
    id: 'carrefour-hipermercado',
    name: 'Carrefour Hipermercado',
    category: 'compras',
    description: 'Hipermercado anexo ao Shopping Campo Grande, ideal para compras de conveniência, farmácia, higiene, lanches rápidos e souvenirs.',
    siteUrl: 'https://www.carrefour.com.br',
    siteLabel: 'carrefour.com.br',
    instagramUrl: 'https://www.instagram.com/carrefourbrasil',
    instagramHandle: '@carrefourbrasil',
    highlightTag: 'Hipermercado & Farmácia',
    addressInfo: 'Av. Afonso Pena, 4909 - Santa Fé (Anexo ao Shopping Campo Grande)',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carrefour+Hipermercado+Shopping+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Carrefour%20Shopping%20Campo%20Grande',
    features: ['Conveniência', 'Drogaria Integrada', 'Adega & Bebidas', 'Estacionamento Coberto'],
  },
  {
    id: 'mirante-stage',
    name: 'Mirante Stage',
    category: 'compras',
    description: 'Espaço de eventos e espetáculos culturais de Campo Grande, com programação de shows e apresentações artísticas.',
    siteUrl: null,
    siteLabel: 'Agenda e ingressos disponíveis via Sympla',
    instagramUrl: 'https://www.instagram.com/mirante.stage',
    instagramHandle: '@mirante.stage',
    highlightTag: 'Shows & Cultura',
    addressInfo: 'R. Doutor Zerbini, 38 - Chácara Cachoeira, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mirante+Stage+Rua+Doutor+Zerbini+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Mirante%20Stage%20Campo%20Grande',
    features: ['Espaço de Eventos', 'Shows & Músicas', 'Próximo ao Grand Park Hotel'],
  },

  // ==================== 04. PARQUES, BIOPARQUE E ÓRGÃOS PÚBLICOS ====================
  {
    id: 'bioparque-pantanal',
    name: 'Bioparque Pantanal',
    category: 'parques',
    description: 'O maior aquário de água doce do mundo e cartão-postal imperdível do MS! Possui 5 milhões de litros de água, túnel panorâmico com peixes gigantes do Pantanal, jacarés e museu interativo.',
    siteUrl: 'https://bioparquepantanal.ms.gov.br',
    siteLabel: 'bioparquepantanal.ms.gov.br (Agendamento & Visitas)',
    instagramUrl: 'https://www.instagram.com/bioparquepantanaloficial',
    instagramHandle: '@bioparquepantanaloficial',
    highlightTag: 'MAIOR AQUÁRIO DE ÁGUA DOCE DO MUNDO',
    addressInfo: 'Av. Afonso Pena, 6277 - Chácara Cachoeira (Parque das Nações Indígenas), Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bioparque+Pantanal+Av+Afonso+Pena+6277+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Bioparque%20Pantanal',
    features: ['Cartão Postal Internacional', 'Túnel Subaquático', 'Agendamento Gratuito pelo Site', 'A 2 min do Grand Park Hotel'],
  },
  {
    id: 'parque-nacoes-indigenas',
    name: 'Parque das Nações Indígenas',
    category: 'parques',
    description: 'Um dos maiores parques urbanos do planeta com 119 hectares de área preservada, lagos, pistas de cooper, animais silvestres livres (capivaras, araras) e museus.',
    siteUrl: 'https://www.imasul.ms.gov.br',
    siteLabel: 'imasul.ms.gov.br (IMASUL)',
    instagramUrl: 'https://www.instagram.com/parquedasnacoesindigenasoficial',
    instagramHandle: '@parquedasnacoesindigenasoficial',
    highlightTag: 'Área Verde Emblemática',
    addressInfo: 'Av. Afonso Pena, s/n - Altos da Afonso Pena, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+das+Na%C3%A7%C3%B5es+Ind%C3%ADgenas+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Parque%20das%20Nacoes%20Indigenas',
    features: ['Pistas de Caminhada & Ciclismo', 'Museu das Culturas Dom Bosco', 'Museu de Arte Contemporânea (MARCO)', 'Natureza Viva'],
  },
  {
    id: 'parque-aguas-do-prosa',
    name: 'Parque Estadual do Prosa',
    category: 'parques',
    description: 'Unidade de conservação integral do bioma Cerrado dentro da malha urbana de Campo Grande, abrigando o Centro de Reabilitação de Animais Silvestres (CRAS).',
    siteUrl: 'https://www.imasul.ms.gov.br',
    siteLabel: 'imasul.ms.gov.br (IMASUL)',
    instagramUrl: null,
    instagramHandle: 'Informações via IMASUL / Governo do Estado',
    highlightTag: 'Preservação do Cerrado',
    addressInfo: 'R. Damião Severino, 100 - Chácara Cachoeira, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Parque+Estadual+do+Prosa+Campo+Grande+MS',
    wazeUrl: 'https://waze.com/ul?q=Parque%20Estadual%20do%20Prosa',
    features: ['Trilhas Ecológicas Guiadas', 'Centro de Reabilitação da Fauna (CRAS)', 'Nascentes e Mata Nativa'],
  },
  {
    id: 'camara-municipal-cg',
    name: 'Câmara Municipal de Campo Grande',
    category: 'parques',
    description: 'Palácio Jaguaribe, sede institucional do Poder Legislativo da capital sul-mato-grossense.',
    siteUrl: 'https://www.camara.ms.gov.br',
    siteLabel: 'camara.ms.gov.br',
    instagramUrl: 'https://www.instagram.com/camaramunicipalcg',
    instagramHandle: '@camaramunicipalcg',
    highlightTag: 'Órgão Público Municipal',
    addressInfo: 'Av. Ricardo Brandão, 1600 - Jatiúca Park, Campo Grande - MS',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=C%C3%A2mara+Municipal+de+Campo+Grande+Av+Ricardo+Brandao+1600',
    wazeUrl: 'https://waze.com/ul?q=Camara%20Municipal%20de%20Campo%20Grande',
    features: ['Poder Legislativo', 'Atendimento ao Cidadão', 'Sessões Plenárias'],
  },
];
